language: go

go:
  - "1.13"

services:
  - mysql

before_install:
  - go get github.com/mattn/goveralls

jobs:
  include:
    - stage: test
      script: make test

    - stage: example
      script:
        - mysql -uroot < mysql/task.ddl
        - make example

    - stage: cover
      script: $GOPATH/bin/goveralls -service=travis-ci