language: go

go:
  - "1.13"

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE fsm;'
  - mysql -e 'CREATE TABLE fsm.task (id VARCHAR(64) NOT NULL, state VARCHAR(64) NOT NULL DEFAULT "", PRIMARY KEY(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;'
    
script: 
  - make test
  - make example